services:
   sql-client:
      image: flink:scala_2.12
      command: bin/sql-client.sh
      networks:
         - iceberg_net
      depends_on:
         - jobmanager
         - mariadb
      environment:
         - |
           FLINK_PROPERTIES=
           jobmanager.rpc.address: jobmanager
           rest.address: jobmanager
   jobmanager:
      user: flink:flink
      build: .
      ports:
         - "8081:8081"
      command: jobmanager
      environment:
         - |
           FLINK_PROPERTIES=
           jobmanager.rpc.address: jobmanager            
      volumes:
         - shared-tmpfs:/tmp/iceberg
      networks:
         - iceberg_net
   taskmanager:
      user: flink:flink
      build: .
      depends_on:
         - jobmanager
      command: taskmanager
      environment:
         - |
           FLINK_PROPERTIES=
           jobmanager.rpc.address: jobmanager
           taskmanager.numberOfTaskSlots: 2            
      volumes:
         - shared-tmpfs:/tmp/iceberg
      networks:
         - iceberg_net
   mariadb:
      container_name: mariadb
      image: mariadb:11
      environment:
         - MYSQL_ROOT_PASSWORD=mypass
      ports:
         - 3306:3306
      networks:
         - iceberg_net
volumes:
   shared-tmpfs:
      driver: local
      driver_opts:
         type: "tmpfs"
         device: "tmpfs"
networks:
   iceberg_net:
