services:
  mariadb-main:
    container_name: mariadb-main
    build:
      context: dockerfiles
      dockerfile: Dockerfile.mariadb
    volumes:
      - mariadbdata:/bitnami/mariadb
      - ./dockerfiles/config/my.cnf:/opt/bitnami/mariadb/conf/my.cnf
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=main_root_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
  mariadb-replica:
    container_name: mariadb-replica
    build:
      context: dockerfiles
      dockerfile: Dockerfile.mariadb
    depends_on:
      - mariadb-main
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb-main
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=main_root_password
    volumes:
      - ./dockerfiles/config/my.cnf:/opt/bitnami/mariadb/conf/my.cnf
  jobmanager:
    user: flink:flink
    container_name: jobmanager
    build:
      context: dockerfiles
      dockerfile: Dockerfile.main
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        execution.checkpointing.interval: 3000
    volumes:
      - mariadbdata:/tmp/iceberg
      - mariadbdata:/tmp/paimon
  taskmanager:
    user: flink:flink
    container_name: taskmanager
    build:
      context: dockerfiles
      dockerfile: Dockerfile.main
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        execution.checkpointing.interval: 3000
    volumes:
      - mariadbdata:/tmp/iceberg
      - mariadbdata:/tmp/paimon
  sql-client:
    user: flink:flink
    container_name: sql-client
    build:
      context: dockerfiles
      dockerfile: Dockerfile.sqlclient
    depends_on:
      - jobmanager
      - mariadb-replica
    environment:
      - MYSQL_HOST=mariadb-replica
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        execution.checkpointing.interval: 3000
    volumes:
      - mariadbdata:/tmp/iceberg
      - mariadbdata:/tmp/paimon
    networks:
      - default
  debezium:
    image: debezium/server:3.0.0.Final
    container_name: debezium
    ports:
      - 8080:8080
    volumes:
      - ./dockerfiles/config/application.properties.mediawiki:/debezium/config/application.properties
    depends_on:
      - mariadb-main
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    volumes:
      - ./dockerfiles/config/kafka-ui.yaml:/etc/kafkaui/dynamic_config.yaml
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
    ports:
      - 8082:8080
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
volumes:
  mariadbdata:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
