services:
   sql-client:
      user: flink:flink
      build:
         context: dockerfiles
         dockerfile: Dockerfile.client
      # command: bin/sql-client.sh -e "SET execution.checkpointing.interval = '3s';"
      networks:
         - iceberg_net
      depends_on:
         - jobmanager
         - mariadb
      environment:
         - MYSQL_HOST=mariadb
         - |
           FLINK_PROPERTIES=
           jobmanager.rpc.address: jobmanager
           rest.address: jobmanager
      volumes:
         - shared-tmpfs:/tmp/iceberg
   jobmanager:
      user: flink:flink
      build:
         context: dockerfiles
         dockerfile: Dockerfile.main
      ports:
         - "8081:8081"
      command: jobmanager
      environment:
         - |
           FLINK_PROPERTIES=
           jobmanager.rpc.address: jobmanager            
      volumes:
         - shared-tmpfs:/tmp/iceberg
      networks:
         - iceberg_net
   taskmanager:
      user: flink:flink
      build:
         context: dockerfiles
         dockerfile: Dockerfile.main
      depends_on:
         - jobmanager
      command: taskmanager
      environment:
         - |
           FLINK_PROPERTIES=
           jobmanager.rpc.address: jobmanager
           taskmanager.numberOfTaskSlots: 2            
      volumes:
         - shared-tmpfs:/tmp/iceberg
      networks:
         - iceberg_net
   mariadb:
      container_name: mariadb
      # image: mariadb:11
      # command: --log-bin=/var/log/mysql/mariadb-bin --binlog-format=ROW
      build:
         context: dockerfiles
         dockerfile: Dockerfile.mariadb
      environment:
         - MYSQL_ROOT_PASSWORD=mypass
      ports:
         - 3306:3306
      networks:
         - iceberg_net
volumes:
   shared-tmpfs:
      driver: local
      driver_opts:
         type: "tmpfs"
         device: "tmpfs"
networks:
   iceberg_net:
